### ISSUE TITLE
Scrape timestamp metrics as value

### ISSUE THREAD

**Issue by minefuto** [opsdis/aci-exporter#12]
**Is your feature request related to a problem? Please describe.**
I want to scrape timestamp metrics as value(not label) from ACI such as modTs.
```
{
   "totalCount":"1",
   "imdata":[
      {
         "infraWiNode":{
            "attributes":{
               -snip-
               "modTs":"2020-04-18T05:24:07.722+00:00",
```

**Describe the solution you'd like**
I think aci-exporter need to translate from "2020-04-18T05:24:07.722+00:00" to unixtime.
 
Do you have any plans to add the above function?
Or is it already implemented?

**Comment by thenodon** [comment]
Hi @minefuto, 
Can you provide the aci config, so I can se the query you are running.
When it comes to recalculate the value there is currently options as value_transform and value_calculation.
A value transform some string value to a float.
```
value_transform:
          'unknown': 0
          'down': 1
          'up': 2
          'link-up': 3
```

A value_calculation can make some simple calculations of the value. This example divide the value (value-string is a placeholder for the value) with 100. 
`value_calculation: "value / 100"`

aci-exporter use https://github.com/Knetic/govaluate to execute the expression like "value / 100". In govaluate it is possible to create addtional "functions" that can be called, see https://github.com/Knetic/govaluate#functions. So it might be possible to create some additional functions for your use case.

**Comment by minefuto** [comment]
Thanks @thenodon,
I think [Knetic/govaluate](https://github.com/Knetic/govaluate/blob/0580e9b47a69125afa0e4ebd1cf93c49eb5a43ec/parsing.go#L249-L251) only supported to transform from `string` to `Time` type.
Not supported from `string` to unixtime(`float`).

I want to detect link flap of ACI.
config.yaml
```yaml
class_queries:
  interface_info:
    class_name: interface_info
    metrics:
      - name: lastLinkStChg
        value_name: ethpmPhysIf.attributes.lastLinkStChg
        type: gauge
    labels:
      - property_name: ethpmPhysIf.attributes.dn
        regex: "^topology/pod-(?P<podid>[1-9][0-9]*)/node-(?P<nodeid>[1-9][0-9]*)/sys/phys-\\[(?P<interface>[^\\]]+)\\]/"
```
prometheus-rules.yml
```yaml
groups:
- name: alert
  rules:
  - alert: "interface flap"
    expr: changes(aci_lastLinkStChg[5m]) > 0
    for: 1m
```
But `lastLinkStChg` cannot scraped because it is `string` such as `2020-04-18T05:24:07.722+00:00`.
So aci-exporter should get `lastLinkStChg` as a unixtime(`float`).

example:
https://github.com/minefuto/aci-exporter/commit/0691f568550d63bf92f347572e8c1addc8949263

**Comment by thenodon** [comment]
I understand your use case and it make sense to understand flapping. I still think it could be done with https://github.com/Knetic/govaluate#functions. 
We could implement a govaluate function like date_to_unixtime(.....) and in your aci config have 
```
class_queries:
  interface_info:
    class_name: interface_info
    metrics:
      - name: lastLinkStChg
        value_name: ethpmPhysIf.attributes.lastLinkStChg
        type: gauge
        value_calculation: "date_to_unixtime(value, "rfc_3339")
    labels:
      - property_name: ethpmPhysIf.attributes.dn
        regex: "^topology/pod-(?P<podid>[1-9][0-9]*)/node-(?P<nodeid>[1-9][0-9]*)/sys/phys-\\[(?P<interface>[^\\]]+)\\]/"
```
The functions needs to be part of the parsing so a refactor of func valueReCalculation(...) needs to be done. I would be preferable that the govaluate function could be "loaded" at start up (reflection) to support custom function in additions to standard functions provided by aci-exporter. 
This is just my thought and I have not done any testing. Would be great to know if there are a general request for this functionality.

**Comment by minefuto** [comment]
Thanks, I understand your idea.
It looks like a good.

**Comment by thenodon** [comment]
@minefuto please checkout branch issue_12 and test the fix. aci-export will now automatically convert date in rfc3339 format to a float. Hopefully all dates are in that format. 
Use the config like:
```
class_queries:
  interface_lastlink_st_chg_to_date:
    class_name: ethpmPhysIf
    metrics:
      - name: lastLinkStChg
        value_name: ethpmPhysIf.attributes.lastLinkStChg
        type: counter
    labels:
      # The field in the json used to parse the labels from
      - property_name: ethpmPhysIf.attributes.dn
        # The regex where the string enclosed in the P<xyz> is the label name
        regex: "^topology/pod-(?P<podid>[1-9][0-9]*)/node-(?P<nodeid>[1-9][0-9]*)/sys/phys-\\[(?P<interface>[^\\]]+)\\]/"
```
