### ISSUE TITLE
It is possible to generate a metric file with empty # HELP and / or # TYPE lines

### ISSUE THREAD

**Issue by JDA88** [opsdis/aci-exporter#25]
**Describe the bug**
If you don’t input the `type` and / or `help` field in the yaml it will successfully generate the metric file but prometheus will fail to scrap it

**To Reproduce**
if you leave commented the `type` and / or `help` lines in the following metric the fille will be generated with empty `# HELP` and / or `# TYPE` lines
```
    metrics:
      - name: test_metric
        value_name: eqptCh.attributes.model
#        type: "gauge"
        unit: "ratio"
#        help: "Returns the kernel space cpu load of a fabric node"
```

**Expected behavior**
**Option1:** The program should detect the yaml file as invalid
**Option2:** The program should replace the missing filed to "default" values `type: "gauge"` / `help: "Missing"`
