### ISSUE TITLE
static_binding_info: value_regex_transformation not working

### ISSUE THREAD

**Issue by camrossi** [opsdis/aci-exporter#33]
I am trying to extract the static biding infos with this class query:

```
      static_binding_info:
        class_name: fvAEPg
        query_parameter: '?rsp-subtree-include=required&rsp-subtree-class=fvRsPathAtt&rsp-subtree=children'
        metrics:
          - name: static_binding
            value_name: fvAEPg.children.[fvRsPathAtt].attributes.encap
            type: gauge
            value_regex_transformation: "vlan-(.*)"
            help: "Static Binding Infos"
        labels:
          - property_name: fvAEPg.attributes.dn
            regex: "^uni/tn-(?P<tenant>.*)/ap-(?P<app>.*)/epg-(?P<epg>.*)"
          - property_name: fvAEPg.attributes.[.*].attributes.tDn
            regex: "^topology/pod-(?P<podid>[1-9][0-9]*)/(protpaths|paths)-(?P<nodeid>[1-9][0-9].*)/pathep-\\[(?P<port>.+)\\]"
          - property_name: fvAEPg.attributes.[.*].attributes.encap
            regex: "^(?P<encap>.*)"
```

The query works but it seems we aren't triggering the `value_regex_transformation`:

I get this error message
`{"level":"info","msg":"could not convert value to float, will return 0.0 ","time":"2023-07-12T03:02:43Z","value":"vlan-110"}` that matches the `toFloat` function Info message and seems the `toFloatTransform` isn't called?

the returned data is 
`aci_static_binding{aci="ACI Fabric2",app="Trex",encap="vlan-110",epg="Trex-2",fabric="fab2",nodeid="203-204",podid="1",port="bm-01-40G_PolGrp",tenant="Trex"} 0`

There are no other error messages so I am not sure why this is happening.
