### ISSUE TITLE
label regex not executed on child class

### ISSUE THREAD

**Issue by camrossi** [opsdis/aci-exporter#34]
I am trying to extract the EPG to Port mapping with this code 
```
  epg_to_port:
    class_name: vlanCktEp
    query_parameter: '?rsp-subtree-include=required&rsp-subtree-class=l2RsPathDomAtt&rsp-subtree=children'
    metrics:
      - name: dynamic_binding
        value_name: vlanCktEp.attributes.pcTag
        type: gauge
    labels:
      - property_name: vlanCktEp.attributes.epgDn
        regex: "^uni/tn-(?P<tenant>.*)/ap-(?P<app>.*)/epg-(?P<epg>.*)"
      - property_name: vlanCktEp.children.[l2RsPathDomAtt].attributes.tDn
        regex: "^topology/pod-(?P<podid>[1-9][0-9]*)/node-(?P<nodeid>[1-9][0-9]+)/sys/conng/path-\\[(?P<interface>[^\\]]+)\\]"
```

But it seems  the ` vlanCktEp.children.[l2RsPathDomAtt].attributes.tDn` label is not processed. 

I found a way to make it work by passing the child in the metric. 
For example if I use this in the metrics value_name `vlanCktEp.children.[l2RsPathDomAtt].attributes.parentSKey` then the `vlanCktEp.children.[l2RsPathDomAtt].attributes.tDn` label is added as well as `vlanCktEp.attributes.epgDn`

Is this expected?

**Comment by camrossi** [comment]
Hi @thenodon, I see what you mean. Let me explain what is the goal here and how I make it work for now 

At times understanding what EPG/VLAN is deployed on which leaf and port is not super easy and also tracking the deployment over time might be a challenge. 
So my idea was as following:

- the vlanCktEp contains  the mapping of an EPG to a VLAN for example (filtered output) this tells me that I have an EPG called `uni/tn-ocp_sr_iov/ap-netop-ocp_sr_iov/epg-default-sriov-aci-cni-eno10` that is mapped to vlan-102 this can be either a static binding or a dynamic binding done via VMM integration 
```
"vlanCktEp": {
    "attributes": {
        "adminSt": "active",
        "dn": "topology/pod-1/node-203/sys/ctx-[vxlan-2457601]/bd-[vxlan-14778374]/vlan-[vlan-102]",
        "encap": "vlan-102",
        "epgDn": "uni/tn-ocp_sr_iov/ap-netop-ocp_sr_iov/epg-default-sriov-aci-cni-eno10",
        "fabEncap": "vxlan-18492",
        "hwId": "95",
        "id": "111",
        "name": "ocp_sr_iov:netop-ocp_sr_iov:default-sriov-aci-cni-eno10",
        "pcTag": "49155",
    }
}
```
- the Child class `l2RsPathDomAtt` tells me the ports where that EPG is deployed to for example for `epg-default-sriov-aci-cni-eno10` I get 1 child (but is 1 child per port where the EPG is deployed)

```
{
    "totalCount": "1",
    "imdata": [
        {
            "l2RsPathDomAtt": {
                "attributes": {
                    "dn": "topology/pod-1/node-203/sys/ctx-[vxlan-2457601]/bd-[vxlan-14778374]/vlan-[vlan-102]/rspathDomAtt-[topology/pod-1/node-203/sys/conng/path-[eth1/34]]",
                    "operStQual": "unspecified",
                    "parentSKey": "111",
                    "tDn": "topology/pod-1/node-203/sys/conng/path-[eth1/34]",
                    "tSKey": "eth1/34",
                }
            }
        }
    ]
}
```
So from the above I know that is on `node-203 eth1/34`

So my idea is to build a table to summarise this information and I thought a smart metric to use for this would have been the pcTAG that identify the EPG within a VRF/Scope as the Metric. 

But clearly this seems not to be working.
I re-wrote the query like this now:

```
      dynamic_binding_info:
        class_name: vlanCktEp
        query_parameter: '?rsp-subtree-include=required&rsp-subtree-class=l2RsPathDomAtt&rsp-subtree=children'
        metrics:
          - name: dynamic_binding
            value_name: vlanCktEp.children.[l2RsPathDomAtt].attributes.operSt
            type: gauge
            value_transform:
              'unknown': 0
              'down': 1
              'up': 2
              'link-up': 3
        labels:
          - property_name: vlanCktEp.attributes.epgDn
            regex: "^uni/tn-(?P<tenant>.*)/ap-(?P<app>.*)/epg-(?P<epg>.*)"
          - property_name: vlanCktEp.attributes.encap
            regex: "^vlan-(?P<vlan>.*)"
          - property_name: vlanCktEp.attributes.pcTag
            regex: "^(?P<pcTag>.*)"
          - property_name: vlanCktEp.children.[l2RsPathDomAtt].attributes.tDn
            regex: "^topology/pod-(?P<podid>[1-9][0-9]*)/node-(?P<nodeid>[1-9][0-9]+)/sys/conng/path-\\[(?P<interface>[^\\]]+)\\]"

```

And it works pretty well:
I can get two important infos here:

1) The EPG to port to VLAN mapping that I can filter across any fabric/EPG
<img width="1380" alt="image" src="https://github.com/opsdis/aci-exporter/assets/16535101/eb169c76-2c8c-4d86-a143-46535085e947">

2) A time line on which port is used by which EPG, still figuring out which visualisation is better but here is an example when I move a VM from one host to another and you can see the ports are going from 203-204 1/1 to 203-204 1/2
<img width="1420" alt="image" src="https://github.com/opsdis/aci-exporter/assets/16535101/7abb36c2-f56a-4d09-8f6c-718171042d66">


Hope this make sense, do you think the way I run the query now is correct then ?
