### ISSUE TITLE
Convert string to float for operSpeed

### ISSUE THREAD

**Issue by ahmedaall** [opsdis/aci-exporter#35]
**Describe the bug**
The exporter is unable to convert operSpeed string values to float.  

**To Reproduce**
```yaml
class_queries:
  interface_info:
    class_name: l1PhysIf
    query_parameter: "?rsp-subtree=children&rsp-subtree-include=stats&rsp-subtree-class=ethpmPhysIf,eqptIngrBytes5min,eqptEgrBytes5min,eqptIngrDropPkts5min,eqptEgrDropPkts5min&query-target-filter=and(ne( l1PhysIf.adminSt, \"down\"))"
    metrics:
# It works here
      - name: interface_oper_state
        value_name: l1PhysIf.children.[ethpmPhysIf].attributes.operSt
        type: gauge
        help: The current operational state of the interface. (0=unknown, 1=down, 2=up, 3=link-up)
        # A string to float64 transform table of the value
        value_transform:
          'down':               0       ## ~ disabled interfaces
          'up':                 1       ## ~ enabled interfaces     

# But not here
      - name: interface_oper_speed
        value_name: l1PhysIf.children.[ethpmPhysIf].attributes.operSpeed
        type: gauge
        help: The current operational speed of the interface, in bits per second.
        value_transform:
          'unknown':            0
          '100M':       100000000
          '1G':        1000000000
          '10G':      10000000000
          '25G':      25000000000
          '40G':      40000000000
          '100G':    100000000000
          '400G':    400000000000
```

**Additional context**
{"level":"info","msg":"could not convert value to float, will return 0.0 ","time":"2023-08-11T09:56:17Z","value":"100G"}
I have this log for all values (1G,10G,etc.)

It works for all attributes of this classes e.g. operSt, but not for operSpeed

**Comment by thenodon** [comment]
Hi @ahmedaall. I can not recreate the problem you have. I think you have some issue with the yaml so the `value_transform` is not executed. Here is my configuration, with additional label section so the result is not just "one" metric.
```yaml
class_queries:
  interface_info:
    class_name: l1PhysIf
    query_parameter: "?rsp-subtree=children&rsp-subtree-include=stats&rsp-subtree-class=ethpmPhysIf,eqptIngrBytes5min,eqptEgrBytes5min,eqptIngrDropPkts5min,eqptEgrDropPkts5min&query-target-filter=and(ne( l1PhysIf.adminSt, \"down\"))"
    metrics:
      - name: interface_oper_speed
        value_name: l1PhysIf.children.[ethpmPhysIf].attributes.operSpeed
        type: gauge
        help: The current operational speed of the interface, in bits per second.
        value_transform:
          'unknown': 0
          '100M': 100000000
          '1G': 1000000000
          '10G': 10000000000
          '25G': 25000000000
          '40G': 40000000000
          '100G': 100000000000
          '400G': 400000000000
    labels:
      - property_name: l1PhysIf.attributes.dn
        regex: "^topology/pod-(?P<podid>[1-9][0-9]*)/node-(?P<nodeid>[1-9][0-9].*)/sys/phys-\\[(?P<port>.+)\\]"
```
The above give the following output:
```
# HELP aci_interface_oper_speed The current operational speed of the interface, in bits per second.
# TYPE aci_interface_oper_speed gauge
aci_interface_oper_speed{aci="dc-fab",fabric="aci_1",nodeid="201",podid="1",port="eth1/35"} 1e+11
aci_interface_oper_speed{aci="dc-fab",fabric="aci_1",nodeid="201",podid="1",port="eth1/36"} 1e+11
aci_interface_oper_speed{aci="dc-fab",fabric="aci_1",nodeid="201",podid="1",port="eth1/1"} 4e+10
aci_interface_oper_speed{aci="dc-fab",fabric="aci_1",nodeid="201",podid="1",port="eth1/2"} 4e+10
aci_interface_oper_speed{aci="dc-fab",fabric="aci_1",nodeid="201",podid="1",port="eth1/3"} 1e+11
aci_interface_oper_speed{aci="dc-fab",fabric="aci_1",nodeid="201",podid="1",port="eth1/4"} 1e+11
.....
```
